theme="base16_default_dark"
# theme="autumn_night"

[editor]
bufferline = "multiple"
line-number = "relative"
auto-save = true
cursorline = true
[editor.file-picker]
hidden = false
[editor.gutters]
layout = ["diagnostics", "line-numbers", "spacer"]
[editor.cursor-shape]
insert="bar"
[editor.soft-wrap]
enable = true

[editor.whitespace]
[editor.whitespace.render]
space = "none"

[keys.normal]
"esc" = ["collapse_selection", "collapse_selection"]
"," = "repeat_last_motion"
";" = "command_mode"
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
tab = ":bn"
S-tab = ":bp"
"S-k" = "hover"
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
y = ":clipboard-yank-join"
Y = ":clipboard-yank"
R = ":clipboard-paste-replace"
d = [":clipboard-yank-join", "delete_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# S-k = ["half_page_up"]
# S-j = ["half_page_down"]
C-g = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw",
    ":reload-all",
    ":set mouse false",
    ":set mouse true",
]
[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
o = ":config-reload"
w = ":w"
q = ":bc"
e = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ":set mouse false",
  ":set mouse true"
]

[keys.select]
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
y = ":clipboard-yank-join"
Y = ":clipboard-yank"
R = ":clipboard-paste-replace"
d = [":clipboard-yank-join", "delete_selection"]
[keys.select.g]
c = "toggle_comments"
