#!/usr/bin/env bash

riverctl spawn pipewire

map() {
    riverctl map normal "$@"
}
map Super Return spawn foot


map Super Q close
map Super+Shift E exit

# input options
touchpad() {
    riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad "$@"
}
touchpad disable-while-typing disabled
touchpad drag enabled
touchpad tap enabled
touchpad scroll-factor 0.8

riverctl keyboard-layout -options "ctrl:nocaps" us

map Super J focus-view next
map Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
map Super+Shift J swap next
map Super Tab focus-previous-tags
map Super+Shift K swap previous

# for monitors
map Super Period focus-output next
map Super Comma focus-output previous
map Super+Shift Period send-to-output next
map Super+Shift Comma send-to-output previous

map Super+Shift S spawn "$HOME/bin/screenshot all"
map Super+Control S spawn "$HOME/bin/screenshot region"

# Super+Return to bump the focused view to the top of the layout stack
map Super+Shift Return zoom

# Super+Alt+{H,J,K,L} to move views
map Super+Alt H move left 100
map Super+Alt J move down 100
map Super+Alt K move up 100
map Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
map Super+Alt+Control H snap left
map Super+Alt+Control J snap down
map Super+Alt+Control K snap up
map Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
map Super+Alt+Shift H resize horizontal -100
map Super+Alt+Shift J resize vertical 100
map Super+Alt+Shift K resize vertical -100
map Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    map Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    map Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    map Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    map Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
map Super 0 set-focused-tags $all_tags
map Super+Shift 0 set-view-tags $all_tags

map Super Space spawn fuzzel
map Super V toggle-float
map Super F toggle-fullscreen


riverctl declare-mode passthrough
map Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

riverctl set-repeat 50 300

riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

map Super H send-layout-cmd rivercarro "main-ratio -0.05"
map Super L send-layout-cmd rivercarro "main-ratio +0.05"

map Super+Shift H send-layout-cmd rivercarro "main-count +1"
map Super+Shift L send-layout-cmd rivercarro "main-count -1"

map Super Up    send-layout-cmd rivercarro "main-location top"
map Super Right send-layout-cmd rivercarro "main-location right"
map Super Down  send-layout-cmd rivercarro "main-location bottom"
map Super Left  send-layout-cmd rivercarro "main-location left"
map Super M     send-layout-cmd rivercarro "main-location monocle"
map Super W     send-layout-cmd rivercarro "main-location-cycle left,monocle"

riverctl default-layout rivercarro
rivercarro -outer-gaps 0 -per-tag &
